#ifndef NNX_CONFIG_HEADER 
#define NNX_CONFIG_HEADER

#include "memory/paging.h"

#define KERNEL_PML4_ENTRY 511ULL
#define GDT_VIRTUAL_ADDRESS ToCanonicalAddress((UINT64)(PDP_COVERED_SIZE * (KERNEL_PML4_ENTRY) + 256 * PD_COVERED_SIZE))
#define IDT_VIRTUAL_ADDRESS ToCanonicalAddress((UINT64)(GDT_VIRTUAL_ADDRESS + PAGE_SIZE_SMALL))
#define FRAMEBUFFER_DESIRED_LOCATION ToCanonicalAddress((UINT64)(IDT_VIRTUAL_ADDRESS + PAGE_SIZE_SMALL))

#endif