#ifndef NNX_CONFIG_HEADER 
#define NNX_CONFIG_HEADER

#include "HAL/paging.h"

#define GDT_VIRTUAL_ADDRESS				ToCanonicalAddress((UINT64)(PDP_COVERED_SIZE * (KERNEL_DESIRED_PML4_ENTRY) + 256 * PD_COVERED_SIZE))
#define IDT_VIRTUAL_ADDRESS				ToCanonicalAddress((UINT64)(GDT_VIRTUAL_ADDRESS + PAGE_SIZE_SMALL))
#define FRAMEBUFFER_DESIRED_LOCATION	ToCanonicalAddress((UINT64)(IDT_VIRTUAL_ADDRESS + PAGE_SIZE_SMALL))

#define STACK_SIZE (16 * PAGE_SIZE)

#endif